"""initial schema

Revision ID: d231429e0e46
Revises: 
Create Date: 2026-06-12 09:47:43.793158

"""
import sqlalchemy as sa
from alembic import op

revision = 'd231429e0e46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE SEQUENCE IF NOT EXISTS email_agent_id_seq")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_digest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('digest_date', sa.Date(), nullable=False),
    sa.Column('sent_to', sa.String(length=30), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_digest_digest_date'), 'daily_digest', ['digest_date'], unique=False)
    op.create_table('email_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('email_address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority_weight', sa.Float(), nullable=False),
    sa.Column('credentials_ref', sa.String(length=500), nullable=True),
    sa.Column('imap_host', sa.String(length=255), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('auth_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_account_email_address'), 'email_account', ['email_address'], unique=True)
    op.create_table('email_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rule_type', sa.String(length=20), nullable=False),
    sa.Column('condition_json', sa.JSON(), nullable=False),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('email_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_agent_id', sa.String(length=30), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('message_id_header', sa.String(length=998), nullable=True),
    sa.Column('mailbox', sa.String(length=255), nullable=False),
    sa.Column('from_email', sa.String(length=320), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('to_json', sa.JSON(), nullable=True),
    sa.Column('cc_json', sa.JSON(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('normalized_text_hash', sa.String(length=64), nullable=True),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_sent_by_user', sa.Boolean(), nullable=False),
    sa.Column('raw_labels', sa.JSON(), nullable=True),
    sa.Column('ai_labels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['email_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'provider_message_id', 'mailbox')
    )
    op.create_index(op.f('ix_email_message_account_id'), 'email_message', ['account_id'], unique=False)
    op.create_index(op.f('ix_email_message_email_agent_id'), 'email_message', ['email_agent_id'], unique=True)
    op.create_index(op.f('ix_email_message_from_email'), 'email_message', ['from_email'], unique=False)
    op.create_index(op.f('ix_email_message_message_id_header'), 'email_message', ['message_id_header'], unique=False)
    op.create_index(op.f('ix_email_message_normalized_text_hash'), 'email_message', ['normalized_text_hash'], unique=False)
    op.create_index(op.f('ix_email_message_provider_message_id'), 'email_message', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_message_provider_thread_id'), 'email_message', ['provider_thread_id'], unique=False)
    op.create_table('mailbox_cursor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('mailbox', sa.String(length=255), nullable=False),
    sa.Column('uidvalidity', sa.Integer(), nullable=True),
    sa.Column('last_uid', sa.Integer(), nullable=True),
    sa.Column('last_history_id', sa.String(length=50), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['email_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'mailbox')
    )
    op.create_index(op.f('ix_mailbox_cursor_account_id'), 'mailbox_cursor', ['account_id'], unique=False)
    op.create_table('email_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_action_log_idempotency_key'), 'email_action_log', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_email_action_log_message_id'), 'email_action_log', ['message_id'], unique=False)
    op.create_table('email_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('extraction_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_attachment_message_id'), 'email_attachment', ['message_id'], unique=False)
    op.create_index(op.f('ix_email_attachment_sha256'), 'email_attachment', ['sha256'], unique=False)
    op.create_table('email_classification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('spam_score', sa.Float(), nullable=True),
    sa.Column('spam_reason', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=True),
    sa.Column('importance_reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('action_required', sa.Boolean(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('digest_summary', sa.Text(), nullable=True),
    sa.Column('suggested_labels', sa.JSON(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('classified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_classification_category'), 'email_classification', ['category'], unique=False)
    op.create_index(op.f('ix_email_classification_message_id'), 'email_classification', ['message_id'], unique=False)
    op.create_table('email_training_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_training_event_label'), 'email_training_event', ['label'], unique=False)
    op.create_index(op.f('ix_email_training_event_message_id'), 'email_training_event', ['message_id'], unique=False)
    op.create_table('email_user_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('previous_labels', sa.JSON(), nullable=True),
    sa.Column('new_labels', sa.JSON(), nullable=True),
    sa.Column('previous_mailbox', sa.String(length=255), nullable=True),
    sa.Column('new_mailbox', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['email_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_user_event_event_type'), 'email_user_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_email_user_event_message_id'), 'email_user_event', ['message_id'], unique=False)
    op.create_table('human_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('review_type', sa.String(length=40), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=True),
    sa.Column('proposed_action_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('decision_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['email_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_message_id'), 'human_review', ['message_id'], unique=False)
    op.create_index(op.f('ix_human_review_status'), 'human_review', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_review_status'), table_name='human_review')
    op.drop_index(op.f('ix_human_review_message_id'), table_name='human_review')
    op.drop_table('human_review')
    op.drop_index(op.f('ix_email_user_event_message_id'), table_name='email_user_event')
    op.drop_index(op.f('ix_email_user_event_event_type'), table_name='email_user_event')
    op.drop_table('email_user_event')
    op.drop_index(op.f('ix_email_training_event_message_id'), table_name='email_training_event')
    op.drop_index(op.f('ix_email_training_event_label'), table_name='email_training_event')
    op.drop_table('email_training_event')
    op.drop_index(op.f('ix_email_classification_message_id'), table_name='email_classification')
    op.drop_index(op.f('ix_email_classification_category'), table_name='email_classification')
    op.drop_table('email_classification')
    op.drop_index(op.f('ix_email_attachment_sha256'), table_name='email_attachment')
    op.drop_index(op.f('ix_email_attachment_message_id'), table_name='email_attachment')
    op.drop_table('email_attachment')
    op.drop_index(op.f('ix_email_action_log_message_id'), table_name='email_action_log')
    op.drop_index(op.f('ix_email_action_log_idempotency_key'), table_name='email_action_log')
    op.drop_table('email_action_log')
    op.drop_index(op.f('ix_mailbox_cursor_account_id'), table_name='mailbox_cursor')
    op.drop_table('mailbox_cursor')
    op.drop_index(op.f('ix_email_message_provider_thread_id'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_provider_message_id'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_normalized_text_hash'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_message_id_header'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_from_email'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_email_agent_id'), table_name='email_message')
    op.drop_index(op.f('ix_email_message_account_id'), table_name='email_message')
    op.drop_table('email_message')
    op.drop_table('email_rule')
    op.drop_index(op.f('ix_email_account_email_address'), table_name='email_account')
    op.drop_table('email_account')
    op.drop_index(op.f('ix_daily_digest_digest_date'), table_name='daily_digest')
    op.drop_table('daily_digest')
    # ### end Alembic commands ###
